# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import subprocess
from time import sleep

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTranslator
from PyQt5.QtWidgets import QApplication, QMenuBar, QStatusBar, QMenu, QAction, QMainWindow
from psutil import sensors_battery
battery = sensors_battery()
battery_path = "C:\WINDOWS\system32\\battery-report.html"
energy_path = "C:\WINDOWS\system32\energy-report.html"
import screen_brightness_control as sbc

#установка яркости

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 642)
        MainWindow.setAutoFillBackground(True)

        # MainWindow.showFullScreen()

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.MainTab = QtWidgets.QWidget()
        self.MainTab.setObjectName("MainTab")
        self.gridLayout = QtWidgets.QGridLayout(self.MainTab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.MainTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Apply = QtWidgets.QPushButton(self.groupBox)
        self.Apply.setEnabled(False)
        self.Apply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Apply.setStyleSheet("DDDD")
        self.Apply.setCheckable(False)
        self.Apply.setAutoExclusive(True)
        self.Apply.setAutoDefault(False)
        self.Apply.setDefault(False)
        self.Apply.setFlat(False)
        self.Apply.setObjectName("Apply")
        self.horizontalLayout_2.addWidget(self.Apply)
        self.Ok = QtWidgets.QPushButton(self.groupBox)
        self.Ok.setEnabled(False)
        self.Ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ok.setCheckable(False)
        self.Ok.setAutoExclusive(True)
        self.Ok.setAutoDefault(False)
        self.Ok.setDefault(False)
        self.Ok.setFlat(False)
        self.Ok.setObjectName("Ok")

        self.trans = QTranslator(MainWindow)


        self.horizontalLayout_2.addWidget(self.Ok)
        self.Cancel = QtWidgets.QPushButton(self.groupBox)
        self.Cancel.setEnabled(False)
        self.Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cancel.setStyleSheet("DDDD")
        self.Cancel.setCheckable(False)
        self.Cancel.setAutoExclusive(True)
        self.Cancel.setAutoDefault(False)
        self.Cancel.setDefault(False)
        self.Cancel.setFlat(False)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.Cancel)
        self.Defualt = QtWidgets.QPushButton(self.groupBox)
        self.Defualt.setEnabled(True)
        self.Defualt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Defualt.setStyleSheet("DDDD")
        self.Defualt.setCheckable(False)
        self.Defualt.setAutoExclusive(True)
        self.Defualt.setAutoDefault(False)
        self.Defualt.setDefault(False)
        self.Defualt.setFlat(False)
        self.Defualt.setObjectName("Defualt")
        self.horizontalLayout_2.addWidget(self.Defualt)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Creat = QtWidgets.QPushButton(self.groupBox)
        self.Creat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Creat.setObjectName("Creat")
        self.gridLayout_7.addWidget(self.Creat, 6, 1, 1, 1)
        self.Fastlnk = QtWidgets.QLabel(self.groupBox)
        self.Fastlnk.setObjectName("Fastlnk")
        self.gridLayout_7.addWidget(self.Fastlnk, 6, 0, 1, 1)
        self.CurrentPercent = QtWidgets.QLabel(self.groupBox)
        self.CurrentPercent.setObjectName("CurrentPercent")
        self.gridLayout_7.addWidget(self.CurrentPercent, 0, 0, 1, 1)
        self.EndWP = QtWidgets.QLabel(self.groupBox)
        self.EndWP.setObjectName("EndWP")
        self.gridLayout_7.addWidget(self.EndWP, 3, 0, 1, 1)
        self.PerBar = QtWidgets.QProgressBar(self.groupBox)
        self.PerBar.setProperty("value", 0)
        self.PerBar.setProperty("textVisible", False)
        self.PerBar.setObjectName("PerBar")
        self.gridLayout_7.addWidget(self.PerBar, 0, 1, 1, 1)
        self.EndPP = QtWidgets.QLabel(self.groupBox)
        self.EndPP.setObjectName("EndPP")
        self.gridLayout_7.addWidget(self.EndPP, 2, 0, 1, 1)

        self.default_EWP = 70
        self.default_Spin7 = 20
        self.default_EWP2 = 15
        self.default_Screen = 50
        self.work = True

        self.spinEWP_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinEWP_2.setObjectName("spinEWP_2")
        self.gridLayout_7.addWidget(self.spinEWP_2, 3, 1, 1, 1)
        self.StartPP = QtWidgets.QLabel(self.groupBox)
        self.StartPP.setObjectName("StartPP")
        self.gridLayout_7.addWidget(self.StartPP, 1, 0, 1, 1)
        self.spinEWP = QtWidgets.QSpinBox(self.groupBox)

        self.spinEWP.setMinimum(self.default_EWP)
        self.spinEWP.setMaximum(80)
        self.spinEWP_2.setMinimum(self.default_EWP2)
        self.spinEWP_2.setMaximum(30)
        self.spinEWP.setObjectName("spinEWP")
        self.gridLayout_7.addWidget(self.spinEWP, 2, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_7.setMinimum(self.default_Spin7)
        self.spinBox_7.setMaximum(40)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_7.addWidget(self.spinBox_7, 1, 1, 1, 1)

        self.spinSren = QtWidgets.QSpinBox(self.groupBox)
        self.spinSren.setValue(self.default_Screen)
        self.spinSren.setMaximum(100)
        self.spinSren.setSingleStep(10)
        self.spinSren.setObjectName("spinSren")

        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 26))
        self.menubar.setObjectName("menubar")
        self.menuLang = QMenu(self.menubar)
        self.menuLang.setObjectName("menuLang")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.menuLang.addAction(self.action)
        self.menuLang.addAction(self.actionEnglish)
        self.menubar.addAction(self.menuLang.menuAction())

        self.gridLayout_7.addWidget(self.spinSren, 5, 1, 1, 1)
        self.Errors = QtWidgets.QLabel(self.groupBox)
        self.Errors.setObjectName("Errors")
        self.gridLayout_7.addWidget(self.Errors, 4, 0, 1, 1)
        self.Lighting = QtWidgets.QLabel(self.groupBox)
        self.Lighting.setObjectName("Lighting")
        self.gridLayout_7.addWidget(self.Lighting, 5, 0, 1, 1)
        self.Scan = QtWidgets.QPushButton(self.groupBox)
        self.Scan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Scan.setObjectName("Scan")
        self.gridLayout_7.addWidget(self.Scan, 4, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.MainTab, "")
        self.HelpTab = QtWidgets.QWidget()
        self.HelpTab.setObjectName("HelpTab")
        self.formLayout = QtWidgets.QFormLayout(self.HelpTab)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.HelpTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FAQ1 = QtWidgets.QLabel(self.groupBox_2)
        self.FAQ1.setObjectName("FAQ1")
        self.verticalLayout.addWidget(self.FAQ1)
        self.AAQ1 = QtWidgets.QLabel(self.groupBox_2)
        self.AAQ1.setObjectName("AAQ1")
        self.verticalLayout.addWidget(self.AAQ1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.tabWidget.addTab(self.HelpTab, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SettingsTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Lang = QtWidgets.QLabel(self.SettingsTab)
        self.Lang.setObjectName("Lang")
        self.horizontalLayout_5.addWidget(self.Lang)
        self.LangSelect = QtWidgets.QComboBox(self.SettingsTab)
        self.LangSelect.setObjectName("LangSelect")
        self.LangSelect.addItem("")
        self.LangSelect.addItem("")
        self.LangSelect.addItem("")
        self.LangSelect.addItem("")
        self.LangSelect.addItem("")
        self.LangSelect.addItem("")
        self.LangSelect.addItem("")
        self.horizontalLayout_5.addWidget(self.LangSelect)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Theme = QtWidgets.QLabel(self.SettingsTab)
        self.Theme.setObjectName("Theme")
        self.horizontalLayout_6.addWidget(self.Theme)
        self.ThemeSelecter = QtWidgets.QComboBox(self.SettingsTab)
        self.ThemeSelecter.setObjectName("ThemeSelecter")
        self.ThemeSelecter.addItem("")
        self.ThemeSelecter.addItem("")
        self.horizontalLayout_6.addWidget(self.ThemeSelecter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.Disable = QtWidgets.QPushButton(self.SettingsTab)
        self.Disable.setObjectName("Disable")
        self.verticalLayout_2.addWidget(self.Disable)
        self.Enable = QtWidgets.QPushButton(self.SettingsTab)
        self.Enable.setObjectName("Enable")
        self.verticalLayout_2.addWidget(self.Enable)
        self.tabWidget.addTab(self.SettingsTab, "")
        self.SupportTab = QtWidgets.QWidget()
        self.SupportTab.setObjectName("SupportTab")
        self.tabWidget.addTab(self.SupportTab, "")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 26))
        self.menubar.setObjectName("menubar")
        self.menuLang = QtWidgets.QMenu(self.menubar)
        self.menuLang.setObjectName("menuLang")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.menuLang.addAction(self.action)
        self.menuLang.addAction(self.actionEnglish)
        self.menubar.addAction(self.menuLang.menuAction())
        self.Defualt.setEnabled(False)
        self.functions()
        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Atutum Battary Manger"))
        self.groupBox.setTitle(_translate("MainWindow", "Battary Manger"))
        self.Apply.setText(_translate("MainWindow", "Apply"))
        self.Ok.setText(_translate("MainWindow", "Ok"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.Defualt.setText(_translate("MainWindow", "Defualt"))
        self.Creat.setText(_translate("MainWindow", "Creat"))
        self.Fastlnk.setText(_translate("MainWindow", "Creat fast input link"))
        self.CurrentPercent.setText(_translate("MainWindow", "Battary persent on start app: "))
        self.EndWP.setText(_translate("MainWindow", "Set ending work persent: "))
        self.EndPP.setText(_translate("MainWindow", "Set end powering persent: "))
        self.StartPP.setText(_translate("MainWindow", "Set start powering persent: "))
        self.Errors.setText(_translate("MainWindow", "Errors (Battery health)"))
        self.Lighting.setText(_translate("MainWindow", "Screen lighting"))
        self.Scan.setText(_translate("MainWindow", "Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), _translate("MainWindow", "Main"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FAQ"))
        self.FAQ1.setText(_translate("MainWindow", "Why i can`t scan my device"))
        self.AAQ1.setText(_translate("MainWindow", "To scan you need run this application with system administrator rights"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HelpTab), _translate("MainWindow", "Help"))
        self.Lang.setText(_translate("MainWindow", "Language"))
        self.LangSelect.setItemText(0, _translate("MainWindow", "English"))
        self.LangSelect.setItemText(1, _translate("MainWindow", "Русский"))
        self.LangSelect.setItemText(2, _translate("MainWindow", "Беларуская мова"))
        self.LangSelect.setItemText(3, _translate("MainWindow", "Spanol"))
        self.LangSelect.setItemText(4, _translate("MainWindow", "Fracia"))
        self.LangSelect.setItemText(5, _translate("MainWindow", "Arabic"))
        self.LangSelect.setItemText(6, _translate("MainWindow", "Chinese"))
        self.Theme.setText(_translate("MainWindow", "Theme"))
        self.ThemeSelecter.setItemText(0, _translate("MainWindow", "Light"))
        self.ThemeSelecter.setItemText(1, _translate("MainWindow", "Black"))
        self.Disable.setText(_translate("MainWindow", "Disable program work"))
        self.Enable.setText(_translate("MainWindow", "Enable program work"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SettingsTab), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SupportTab), _translate("MainWindow", "Support"))
        self.menuLang.setTitle(_translate("MainWindow", "Language"))
        self.action.setText(_translate("MainWindow", "Русский"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))

class Thread(QtCore.QThread):
    updateSignal = QtCore.pyqtSignal(str)

    def __init__(self, status, parent=None):
        super(Thread, self).__init__(parent)
        self.status = status
        self.i = 0

    def run(self):
        while True:
            self.updateSignal.emit(f'{self.status}{self.i}')
            self.i = sensors_battery().percent
            self.msleep(1000)


class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self, status):
        super().__init__()
        self.setupUi(self)

        self.status = status
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(210, 150, 510, 24))

        self.statusUpgrader(status)
        self.start_thread()
    def statusUpgrader(self, status):
        self.progress.setValue(int(status))

    def exit(self):
        raise SystemExit(1)

    def start_thread(self):
        self.thread = Thread(self.status)
        self.thread.updateSignal.connect(self.statusUpgrader)
        self.thread.start()
    def functions(self):
        self.Scan.clicked.connect(self.scan)
        self.spinEWP.valueChanged.connect(self.valid)
        self.spinEWP_2.valueChanged.connect(self.valid)
        self.spinSren.valueChanged.connect(self.valid)
        self.spinBox_7.valueChanged.connect(self.valid)
        self.Enable.clicked.connect(self.valid)
        self.Disable.clicked.connect(self.valid)
        self.Defualt.clicked.connect(self.dev)
        self.Apply.clicked.connect(self.ApplyW)
        self.Ok.clicked.connect(self.ApplyW)
        self.Cancel.clicked.connect(self.dev)
        self.Enable.clicked.connect(lambda: self.EnableW(state=True))
        self.Disable.clicked.connect(lambda: self.EnableW(state=False))

    def EnableW(self, state):
        if state is True:
            self.work = state
        if state is False:
            self.work = False


    def ApplyW(self):
        self.Apply.setEnabled(False)
        self.Ok.setEnabled(False)
        self.Cancel.setEnabled(False)
        self.Defualt.setEnabled(False)
        if self.spinSren.valueChanged:
            sbc.set_brightness(self.spinSren.value())
        with open("config.json", 'w') as f:
            f.write("{\n")
            f.write(f'   "Default SPP": "{self.default_Spin7}",\n')
            f.write(f'   "Default EPP": "{self.default_EWP}",\n')
            f.write(f'   "Default EWP": "{self.default_EWP2}",\n')
            f.write(f'   "Default SL": "{self.default_Screen}",\n')
            f.write(f'   "Work": "{self.work}"\n')
            f.write("}")
            f.close()

    def valid(self):
        self.Apply.setEnabled(True)
        self.Ok.setEnabled(True)
        self.Cancel.setEnabled(True)
        self.Defualt.setEnabled(True)
    def dev(self):
        self.spinBox_7.setValue(self.default_Spin7)
        self.spinSren.setValue(self.default_Screen)
        self.spinEWP.setValue(self.default_EWP)
        self.spinEWP_2.setValue(self.default_EWP2)
        self.Defualt.setEnabled(False)
        self.Cancel.setEnabled(False)
        self.Apply.setEnabled(False)
        self.Ok.setEnabled(False)
    def scan(self):
        # os.system('powershell Start-Process "powercfg energy" -Verb RunAs')
        if subprocess.check_output('powershell Start-Process "powercfg energy" -Verb RunAs') != "":
            os.system("C:\WINDOWS\system32\energy-report.html")


status = 0

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    w = MainWindow(status)
    w.show()
    sys.exit(app.exec())
